### ISSUE TITLE
Dynamic Surroundings compat crash

### ISSUE THREAD

**Issue by vtesterlwg** [asiekierka/MageMC#9]
Me again! MAGE seems to crash with the latest version of dynamic surroundings on forge 2806 (+ liteloader). mods:

DynamicSurroundings-1.12.2-3.5.4.1BETA.jar
OreLib-1.12.2-3.5.2.0BETA.jar
MAGE-0.2.4.jar

[18:03:26] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@38979a58:
java.lang.NullPointerException: null
	at org.orecruncher.dsurround.client.handlers.scanners.RandomBlockEffectScanner.interestingBlock(RandomBlockEffectScanner.java:70) ~[RandomBlockEffectScanner.class:?]
	at org.orecruncher.dsurround.lib.scanner.Scanner.func_73660_a(Scanner.java:150) ~[Scanner.class:?]
	at org.orecruncher.dsurround.client.handlers.AreaBlockEffectsHandler.process(AreaBlockEffectsHandler.java:56) ~[AreaBlockEffectsHandler.class:?]
	at org.orecruncher.dsurround.client.handlers.EffectManager.onTick(EffectManager.java:172) ~[EffectManager.class:?]
	at org.orecruncher.dsurround.client.handlers.EffectManager.clientTick(EffectManager.java:182) ~[EffectManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_11]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_11]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_11]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:03:26] [Client thread/ERROR]: Index: 4 Listeners:
[18:03:26] [Client thread/ERROR]: 0: HIGHEST
[18:03:26] [Client thread/ERROR]: 1: ASM: class org.orecruncher.lib.chunk.ClientChunkCache clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:03:26] [Client thread/ERROR]: 2: ASM: DiagnosticHandler{name=Diagnostics} tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:03:26] [Client thread/ERROR]: 3: NORMAL
[18:03:26] [Client thread/ERROR]: 4: ASM: class org.orecruncher.dsurround.client.handlers.EffectManager clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:03:26] [Client thread/ERROR]: 5: ASM: class org.orecruncher.dsurround.client.sound.MusicFader onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:03:26] [Client thread/ERROR]: 6: ASM: net.minecraftforge.common.ForgeInternalHandler@27bfba2a checkSettings(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:03:26] [Client thread/ERROR]: 7: ASM: class org.orecruncher.dsurround.client.sound.BackgroundMute clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:03:26] [Client thread/ERROR]: 8: LOW
[18:03:26] [Client thread/ERROR]: 9: ASM: org.orecruncher.dsurround.client.sound.SoundEngine@61598d13 clientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:03:26] [Client thread/ERROR]: 10: LOWEST
[18:03:26] [Client thread/ERROR]: 11: ASM: DiagnosticHandler{name=Diagnostics} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:03:31] [Client thread/INFO]: Applying holder lookups
[18:03:31] [Client thread/INFO]: Holder lookups applied
[18:03:39] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at org.orecruncher.dsurround.client.handlers.scanners.RandomBlockEffectScanner.interestingBlock(RandomBlockEffectScanner.java:70) ~[RandomBlockEffectScanner.class:?]
	at org.orecruncher.dsurround.lib.scanner.Scanner.func_73660_a(Scanner.java:150) ~[Scanner.class:?]
	at org.orecruncher.dsurround.client.handlers.AreaBlockEffectsHandler.process(AreaBlockEffectsHandler.java:56) ~[AreaBlockEffectsHandler.class:?]
	at org.orecruncher.dsurround.client.handlers.EffectManager.onTick(EffectManager.java:172) ~[EffectManager.class:?]
	at org.orecruncher.dsurround.client.handlers.EffectManager.clientTick(EffectManager.java:182) ~[EffectManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_11]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_11]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_11]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by BynariStar** [comment]
I'm running MAGE 0.2.4 with Dynamic Surroundings 3.5.4.2 on Forge 2807 without Liteloader and it seems to be fine. Perhaps one of the versions or Liteloader causes the issue?
